version: '3.8'
services:
  rw-proxy:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - rw-target
    networks:
      - rw_network

  rw-target:
    image: scienv-jupyter:latest
    ports:
      - "8888:8888"
    networks:
      - rw_network
    environment:
      - JUPYTER_ENABLE_LAB=yes
    platform: linux/arm64

networks:
  rw_network:
