version: '3.8'
services:
  rw-proxy:
    build: ghcr.io/reproduce-work/rw-nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/_rwproj/
    depends_on:
      - rw-target
    networks:
      - rw_network

  rw-target:
    image: scienv-jupyter:latest
    ports:
      - "8888:8888"
    networks:
      - rw_network
    environment:
      - JUPYTER_ENABLE_LAB=yes

networks:
  rw_network:
